name: BSESettings
Settings:
  BSEBroadcastInterfaceName: "127.0.0.1" 
  BSEBroadcastMulticastIP: "224.0.0.1"
  BSEBroadcastPort: 8080
  DestinationBroadcastInterface: "127.0.0.1"
  DestinationMulticastIP: "239.255.255.255"
  BindingPort: 8081 
  DestinationPort: 8083
